config/routes.rb
Wormies::Application.routes.draw do

  root :to => "home#index"

  match 'launch' => "home#launch"

  resources :clubs
  match 'clubs/:id/admin' => 'clubs#admin'

end

app/models/club.rb
require 'opentok'

class Club < ActiveRecord::Base
  validates :volume_id, :start_time, :admin_password, :admin_name, :presence => true

  before_create :generate_session

  scope :future, lambda { where("start_time > ?", Time.now ) }

  default_scope order("start_time ASC").future

  private
    def generate_session
      opentok = OpenTok::OpenTokSDK.new APP_CONFIG['opentok_api_key'], APP_CONFIG['opentok_api_secret'], :api_url => "https://api.opentok.com/hl"

      self.session_id = opentok.create_session.to_s 
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clubs_controller.rb
require 'opentok'

class ClubsController < ApplicationController

  before_filter :authenticate, :only => [:admin]
  before_filter :init_opentok, :only => [:show, :admin]

  # GET /clubs
  # GET /clubs.json
  def index
    @clubs = Club.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clubs }
    end
  end

  # GET /clubs/1
  # GET /clubs/1.json
  def show
    @club = Club.find(params[:id])
    @moderator = false
    @token = generate_token OpenTok::RoleConstants::PUBLISHER

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @club }
    end
  end


  def admin
    @club = Club.find(params[:id])
    @moderator = true
    @token = generate_token OpenTok::RoleConstants::MODERATOR

    respond_to do |format|
      format.html { render :action => "show" }
      format.json { render :json => @club }
    end
  end

  # GET /clubs/new
  # GET /clubs/new.json
  def new
    @club = Club.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @club }
    end
  end

  # GET /clubs/1/edit
  def edit
    @club = Club.find(params[:id])
  end

  # POST /clubs
  # POST /clubs.json
  def create
    @club = Club.new(params[:club])

    respond_to do |format|
      if @club.save
        format.html { redirect_to @club, :notice => 'Club was successfully created.' }
        format.json { render :json => @club, :status => :created, :location => @club }
      else
        format.html { render :action => "new" }
        format.json { render :json => @club.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /clubs/1
  # PUT /clubs/1.json
  def update
    @club = Club.find(params[:id])

    respond_to do |format|
      if @club.update_attributes(params[:club])
        format.html { redirect_to @club, :notice => 'Club was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @club.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1
  # DELETE /clubs/1.json
  def destroy
    @club = Club.find(params[:id])
    @club.destroy

    respond_to do |format|
      format.html { redirect_to clubs_url }
      format.json { head :ok }
    end
  end

  private
  def init_opentok
    @opentok = OpenTok::OpenTokSDK.new APP_CONFIG['opentok_api_key'], APP_CONFIG['opentok_api_secret'], :api_url => "https://api.opentok.com/hl"
  end

  def generate_token(role)
    @opentok.generate_token :session_id => @club.session_id, :role => role
  end

  def authenticate
    @club = Club.find(params[:id])

    authenticate_or_request_with_http_basic do |username, password|
      username == @club.admin_name && password == @club.admin_password
    end

    session[:user_id] = @club.admin_name
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @clubs = Club.select("id, admin_name, start_time, volume_id").all
    @club = Club.new
  end

  def launch
    render :action => 'launch', :layout => 'splash'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/clubs/_form.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag "token-input" %>
  <%= stylesheet_link_tag "forms" %>
  <%= javascript_include_tag "https://raw.github.com/loopj/jquery-tokeninput/master/src/jquery.tokeninput.js" %>
  <%= javascript_include_tag "clubs/form" %>
<% end %>

<%= form_for(@club) do |f| %>
  <% if @club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@club.errors.count, "error") %> prohibited this club from being saved:</h2>

      <ul>
      <% @club.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="clearfix">
    <%= f.label :volume_id, "Book" %>
    <div class="input">
      <%= f.text_field :volume_id %>
    </div>
  </div>
  <div class="clearfix">
    <%= f.label :admin_name, "Your Name" %>
    <div class="input">
      <%= f.text_field :admin_name %>
    </div>
  </div>
  <div class="clearfix">
    <%= f.label :admin_password, "Password" %>
    <div class="input">
      <%= f.password_field :admin_password %>
    </div>
  </div>
  <div class="clearfix">
    <%= f.label :start_time %>
    <div class="input">
      <%= f.datetime_select :start_time, { :default => 2.days.from_now, :use_short_month => true, :minute_step => 15, :start_year => Time.now.year }, { :class => "start_time" } %>
    </div>
  </div>
  <div class="clearfix actions">
    <div class="input">
      <%= f.submit :class => "btn primary" %>
    </div>
  </div>
<% end %>

app/views/clubs/edit.html.erb
<h1>Editing club</h1>

<%= render 'form' %>

<%= link_to 'Show', @club %> |
<%= link_to 'Back', clubs_path %>

app/views/clubs/index.html.erb
<h1>Listing clubs</h1>

<table>
  <tr>
    <th>Start time</th>
    <th>Volume</th>
    <th></th>
  </tr>

<% @clubs.each do |club| %>
  <tr>
    <td><%= club.start_time %></td>
    <td><%= club.volume_id %></td>
    <td><%= link_to 'Show', club %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Club', new_club_path %>

app/views/clubs/new.html.erb
<%= render 'form' %>

app/views/clubs/show.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag "clubs" %>
  <%= javascript_include_tag "http://static.opentok.com/v0.91/js/TB.min.js" %>
  <%= javascript_include_tag "http://twitter.github.com/bootstrap/1.3.0/bootstrap-modal.js" %>
  <%= javascript_include_tag "clubs/show" %>
  <script type="text/javascript">


    window.app_config = {
      club: <%= @club.to_json.html_safe %>,
      is_moderator: <%= @moderator %>,

      session: TB.initSession("<%= @club.session_id %>"),

      opentok_api_key: <%= APP_CONFIG['opentok_api_key'] %>,
      opentok_token: "<%= @token %>",
    }
</script>
<% end %>

<div class="meeting-head">
  <div class="row">
    <div class="span11 club media-grid"></div>
    <div class="span5 panel"></div>
  </div>
</div>

<% if @moderator %>
  <div class="stage moderator"></div>
<% else %>
  <div class="stage non-moderator"></div>
<% end %>

app/views/home/index.html.erb
<%= content_for :head do %>
  <%= stylesheet_link_tag "home" %>
  <script type="text/javascript">
    var clubs = new Wormies.Collections.ClubCollection();


    $(document).ready(function() {

      var club_list = new Wormies.Views.ClubListView({
        "el": $(".club-list"),
        "collection": clubs
      });

      clubs.add(<%= @clubs.to_json.html_safe %>);
    });
  </script>
<% end %>


<div class="row">
  <div class="span9 upcoming-meetings">
    <h3>Upcoming meetings</h3>
    <ul class="club-list media-grid"></ul>
  </div>
  <div class="span7 sidebar">
    <p>Host live, face to face book clubs.<br />It's easy and free.</p>
    <%= link_to "Create a club »" , new_club_path, :class => "create btn primary large" %>
  </div>
</div>

app/views/home/launch.html.erb
<%= content_for :head do %>
  <meta property="og:title" content="Wormies - Social Video Book Clubs" /><meta property="og:type" content="company" /><meta property="og:site_name" content="Wormies" /><meta property="og:url" content="http://www.wormi.es" /><meta property="og:image" content="null" /><meta property="og:description" content="Imagine what someone else would want to post on your wall about signing up for your project." />
<% end %>

<div rel="M9SQW1SQ" class="lrdiscoverwidget" data-logo="on" data-background="on" data-share-url="www.wormi.es/launch" data-css=""></div><script type="text/javascript" src="http://launchrock-ignition.s3.amazonaws.com/ignition.1.1.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wormies</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= yield :head %>
    <%= csrf_meta_tags %>
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-27100860-1']);
      _gaq.push(['_setDomainName', 'wormi.es']);
      _gaq.push(['_trackPageview']);

      (function() {
       var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
       ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
       var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
       })();

</script>
</head>
<body>


  <div class="wrapper">

    <div class="header">
      <a href="/">
        <%= image_tag "wormies.png" %>
      </a>
      <h2>Face to face online book clubs.</h2>
    </div>

    <div class="container">
      <%= yield %>
    </div>

    <div class="push"></div>

  </div>

  <div class="footer">
    <div class="container">
      <%= image_tag "wormies.png" %>
      <span class="email">
        email us | <a href="mailto:contact@wormi.es">contact@wormi.es</a>
      </span>
    </div>
  </div>

</body>
</html>

app/views/layouts/splash.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wormies</title>
  <%= javascript_include_tag "application" %>
  <%= yield :head %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>

</body>
</html>